version: "3.3"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: react_frontend
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/usr/app
        command: ["npm","run","test"]
